import type { Person } from "./types"

/** Splits a role into display lines for the multi-line role label in person list rows. */
export function getRoleLines(role: Person["role"]): string[] {
  if (Array.isArray(role)) return role
  const words = role.split(" ")
  return words.length === 4
    ? [words[0], words[1] + " " + words[2], words[3]]
    : words
}

/** Flattens a role into a single display string for the vertical role strip. */
export function getRoleText(role: Person["role"]): string {
  return Array.isArray(role) ? role.join(" ") : role
}

/** Returns a new array of people sorted alphabetically by name. */
export function sortByName(people: Person[]): Person[] {
  return [...people].sort((a, b) => a.name.localeCompare(b.name))
}

// ── Team (About page) ────────────────────────────────────────────────────────
export const teamData: Person[] = [
  { id: 1, name: "Anjana",             pronouns: "She/her", role: ["Content Manager", "Editor"], photo: "/team-pics/Anjana.jpg", languages: ["Malayalam", "English", "Hindi"], bio: "Anjana is a recent graduate and researcher keen on exploring the intersections of media, culture and politics through a critical lens. Her recent academic work involves examining regional belonging and politics in India through cinema. As a co-founder of the Sassafras Initiative, she leads and contributes to the Content Management and Editing team, drawing on her previous experience in journalism. Through the Sassafras Initiative, she aims to engage with areas overlooked by traditional academia and to bring forth meaningful and informed public discourse." },
  { id: 2, name: "Anna Phaidra",       pronouns: "She/they", role: ["Arts and Design Editor", "Arts and Visual Language"], photo: "/team-pics/Anna.jpg", personalLink: "www.annaphaidra.com (currently not functional but will be soon!); Instagram: @annaphaidra", languages: ["English", "Dutch", "French"], bio: "Anna Phaidra is an award-winning artist and researcher specializing in illustration, woodcarving, and installation. Their work attends to living, extinct, and speculative beings through an interdisciplinary lens—bringing together historical symbolism and folklore with environmental humanities research. They hold a BA and BFA at Leiden University and the Royal Academy of Art (KABK) in The Hague respectively, and are currently completing their MA project on geological worlding and unworlding at Humboldt University. They are one of the founders of Sassafras—an experimental digital publication platform to be launched in June 2026, and volunteer as librarian for Colorama Print. They live and work in Berlin." },
  { id: 3, name: "Barra MacMahon",     pronouns: "He/him", role: ["Arts and Design Editor", "Website Developer"], photo: "/team-pics/Barra.jpg", bio: "Barra MacMahon is a web developer and musician hailing from the west of Ireland. He studied Contemporary Modern Music with a focus on vocal performance at BIMM Dublin before moving to Berlin and learning to code at 42 Berlin. In his spare time he plays guitar with Ruth Mac and enjoys tinkering with audio tech. His work blends his love for playful sound design and gritty guitar shoegaze music." },
  { id: 4, name: "Chenlu Ni",          pronouns: "", role: "Designer/Web Developer", photo: "/team-pics/chenlu.jpg", bio: "" },
  { id: 5, name: "Diana Rudic",        pronouns: "She/her", role: ["Content Management", "Editor"], photo: "/team-pics/Diana.jpg", languages: ["English", "French", "Serbo-Croatian"], bio: "Diana is a student and researcher whose interests include analyzing the intersections of media, culture industries, identity formation, statecraft, and affective politics. She holds degrees in economics, political science, and psychology, and she is currently finishing her Master's in Global Studies. Her professional experiences have involved working across editorial, educational, and think tank settings. At present, she is completing a research project on political humor in the age of the attention economy and rising authoritarianism." },
  { id: 6, name: "Gabrielle Francois", pronouns: "She/her", role: ["Social Media, Branding", "and Promotion"], photo: "/team-pics/Gabrielle.jpg", personalLink: "www.linkedin.com/in/gabriellemfrancois", bio: `Gabrielle is fascinated by the things that survive empire: laws, institutions, stories, superstitions, and the people who navigate them all at once. Raised in Trinidad and Tobago, her work explores the productive tensions between colonial institutions, legal frameworks, and governance structures on the one hand, and the everyday sociocultural practices through which people create meaning, belonging, and community on the other. Drawing on literature, oral traditions, folklore, and superstitious practices as archives of knowledge, Gabrielle brings these sources into conversation with scholarship on migration, citizenship, and land governance. Her approach has been shaped by encounters with diverse traditions of knowledge production across the Global North and Global South, including in Trinidad and Tobago, South Africa, Germany, and the United States. Professionally, she has worked in the public sector, law, and international development, experiences that continue to inform her interest in the relationship between institutions, power, and everyday life.\nGabrielle is also Co-founder and Director of Social Media and Branding at Sassafras Initiative, a role that complements her broader interest in how ideas, identities, and forms of knowledge are communicated, negotiated, and reproduced across different social worlds.` },
  { id: 7, name: "Javiera",            pronouns: "She/her", role: ["Project Management", "Content Management"], photo: "/team-pics/Javiera.jpg", languages: ["Spanish", "English"], bio: "Javiera is a history and social sciences researcher whose work explores themes of home, homemaking, migration, and belonging, tracing the emotional, spatial, and material dimensions of everyday life across borders. She holds a BA in History and is currently completing an MA in Global Studies, with a focus on homemaking among Latin migrant women's communities in Germany. Outside academia, she uses illustration as a means of exploring stories and experiences that often escape written language. She is one of the co-founders of Sassafras." },
  { id: 8, name: "Malin Menzel",       pronouns: "She/her", role: "Event Coordinator", photo: "/team-pics/Malin.jpg", bio: "Malin works at the intersection of decolonial and intersectional feminist thought, with particular interest in sexual and reproductive health and rights. She holds a BA in International Relations from the University of Groningen and an MA in Global Studies from Humboldt University of Berlin, and has worked across NGOs and international organizations, including UNAIDS, on human rights and sexual and reproductive health. She also carries a strong regional interest in Latin America, having studied and worked in Colombia, Argentina, and Guatemala. Professionally, she works on public sector projects, particularly in climate while integrating feminist and intersectional perspectives into that work. Creatively, she is into all things textile, drawn to handicraft and textile art as sociological objects and to the forms of female community that build up around them. She joined Sassafras to channel her constant analyzing of the world into something more productive." },
]

// ── Contributors (Current Issue page) ──────────────────────────────────────────
export const contributorsData: Person[] = [
  { id: 1, name: "Gabrielle Francois", pronouns: "She/her", role: "", photo: "/team-pics/Gabrielle.jpg", bio: `Gabrielle is fascinated by the things that survive empire: laws, institutions, stories, superstitions, and the people who navigate them all at once. Raised in Trinidad and Tobago, her work explores the productive tensions between colonial institutions, legal frameworks, and governance structures on the one hand, and the everyday sociocultural practices through which people create meaning, belonging, and community on the other. Drawing on literature, oral traditions, folklore, and superstitious practices as archives of knowledge, Gabrielle brings these sources into conversation with scholarship on migration, citizenship, and land governance. Her approach has been shaped by encounters with diverse traditions of knowledge production across the Global North and Global South, including in Trinidad and Tobago, South Africa, Germany, and the United States. Professionally, she has worked in the public sector, law, and international development, experiences that continue to inform her interest in the relationship between institutions, power, and everyday life.\nGabrielle is also Co-founder and Director of Social Media and Branding at Sassafras Initiative, a role that complements her broader interest in how ideas, identities, and forms of knowledge are communicated, negotiated, and reproduced across different social worlds.` },
  { id: 2, name: "Kalifa Lovelace",    pronouns: "She/her", role: "", photo: "/team-pics/Kalifa.jpg", bio: `Kalifa Lovelace is a writer from Trinidad and Tobago whose work centers the Caribbean female experience — its loves, losses, and connections across the familial, romantic, and personal. Drawing on the rich landscape of Caribbean life, her writing moves between poetry and fiction. Her personal interest align with science fiction and speculative fiction as lenses through which to explore these themes.\nHer work has appeared in the First Nations Poetry Magazine, where her poem "Knots" was published, and in the anthology Tales of Root, Silk & Bone, which features her poems "Freedom of the Whore" and "The River Mother Repents Her Ocean Love." By profession, Kalifa is a legal practitioner in Trinidad and Tobago.` },
  { id: 3, name: "Diana Rudic",        pronouns: "She/her", role: "", photo: "/team-pics/Diana.jpg", bio: "Diana is a student and researcher whose interests include analyzing the intersections of media, culture industries, identity formation, statecraft, and affective politics. She holds degrees in economics, political science, and psychology, and she is currently finishing her Master's in Global Studies. Her professional experiences have involved working across editorial, educational, and think tank settings. At present, she is completing a research project on political humor in the age of the attention economy and rising authoritarianism." },
  { id: 4, name: "Anna Phaidra",       pronouns: "She/they", role: "", photo: "/team-pics/Anna.jpg", bio: "Anna Phaidra is an award-winning artist and researcher specializing in illustration, woodcarving, and installation. Their work attends to living, extinct, and speculative beings through an interdisciplinary lens—bringing together historical symbolism and folklore with environmental humanities research. They hold a BA and BFA at Leiden University and the Royal Academy of Art (KABK) in The Hague respectively, and are currently completing their MA project on geological worlding and unworlding at Humboldt University. They are one of the founders of Sassafras—an experimental digital publication platform to be launched in June 2026, and volunteer as librarian for Colorama Print. They live and work in Berlin." },
  { id: 5, name: "Javiera",            pronouns: "She/her", role: "", photo: "/team-pics/Javiera.jpg", bio: "Javiera is a history and social sciences researcher whose work explores themes of home, homemaking, migration, and belonging, tracing the emotional, spatial, and material dimensions of everyday life across borders. She holds a BA in History and is currently completing an MA in Global Studies, with a focus on homemaking among Latin migrant women's communities in Germany. Outside academia, she uses illustration as a means of exploring stories and experiences that often escape written language. She is one of the founders of Sassafras." },
  { id: 6, name: "Barra MacMahon",     pronouns: "He/him", role: "", photo: "/team-pics/Barra.jpg", bio: "Barra MacMahon is a web developer and musician hailing from the west of Ireland. He studied Contemporary Modern Music with a focus on vocal performance at BIMM Dublin before moving to Berlin and learning to code at 42 Berlin. In his spare time he plays guitar with Ruth Mac and enjoys tinkering with audio tech. His work blends his love for playful sound design and gritty guitar shoegaze music." },
  { id: 7, name: "Anjana",             pronouns: "She/her", role: "", photo: "/team-pics/Anjana.jpg", bio: "Anjana is a recent graduate and researcher keen on exploring the intersections of media, culture and politics through a critical lens. Her recent academic work involves examining regional belonging and politics in India through cinema. As a co-founder of the Sassafras Initiative, she leads and contributes to the Content Management and Editing team, drawing on her previous experience in journalism. Through the Sassafras Initiative, she aims to engage with areas overlooked by traditional academia and to bring forth meaningful and informed public discourse." },
  { id: 8, name: "Anusha",             pronouns: "", role: "", photo: "/team-pics/anusha.jpeg", bio: `Hey there! I’m Anusha, a globally curious, purpose-fuelled individual. A social worker with a post graduate in international law by training, a non-linear professional who has held positions in NGOs, museums, schools and research forums in London, South India and remotely in Australia. Over time, I shifted my focus from classic human rights advocacy towards impact, change and creative practices.\nCurrently navigating a career transition, I build and implement projects for structural change via my writing. I work at the intersection of feminism, human rights law and modern philanthropy. Drawing on my writing experience from my academic world, I focus on storytelling as a tool to systematic change that can be made practical from preventive approaches to global collaboration.\nMy dedication to gender equity is also rooted in my heritage. Growing up in South India, despite a privileged upbringing, I grew up feeling pretty frustrated about how traditional gender roles oppress women and girls. Understanding these dynamics through a border lens shapes me to create changes.` },
  { id: 9, name: "Malin Menzel",       pronouns: "She/her", role: "", photo: "/team-pics/Malin.jpg", bio: "Malin works at the intersection of decolonial and intersectional feminist thought, with particular interest in sexual and reproductive health and rights. She holds a BA in International Relations from the University of Groningen and an MA in Global Studies from Humboldt University of Berlin, and has worked across NGOs and international organizations, including UNAIDS, on human rights and sexual and reproductive health. She also carries a strong regional interest in Latin America, having studied and worked in Colombia, Argentina, and Guatemala. Professionally, she works on public sector projects, particularly in climate while integrating feminist and intersectional perspectives into that work. Creatively, she is into all things textile, drawn to handicraft and textile art as sociological objects and to the forms of female community that build up around them. She joined Sassafras to channel her constant analyzing of the world into something more productive." },
]
